climate_corp_people = [
    'Gregory Smirin',
    'David Friedberg',
    'Andy Mutz',
    'Tina Harrison',
    'David Leyva',
    'Erica Clawson',
    'Nitin Verma',
    'Brian Zimmer',
    'Andrea Wendel',
    'Sunil Abraham',
    'Joseph Chong',
    'Tristan dOrgeval',
    'Daniel Zook',
    'Sang Park',
    'Jason Fain',
    'Aditya Rao',
    'Stephan Hoyer',
    'May Cheung',
    'Aman Thakral',
    'Adeline Tai',
    'Nathan Mehl'
]

climate_corp_urls = [
    'http://www.linkedin.com/in/smirin',
    'http://www.linkedin.com/in/davidfriedberg',
    'http://www.linkedin.com/in/amutz',
    'http://www.linkedin.com/in/tinamharrison',
    'http://www.linkedin.com/in/dleyva3',
    'http://www.linkedin.com/in/ericaclawson',
    'http://www.linkedin.com/in/nitinonrails',
    'http://www.linkedin.com/in/bzimmer',
    'http://www.linkedin.com/in/andrealouisewendel',
    'http://www.linkedin.com/in/ssabraham',
    'http://www.linkedin.com/in/josephchong',
    'http://www.linkedin.com/in/tdorgeval',
    'http://www.linkedin.com/in/danielzook',
    'http://www.linkedin.com/in/sangpark',
    'http://www.linkedin.com/in/jasonfain',
    'http://www.linkedin.com/in/adityacrao',
    'http://www.linkedin.com/in/stephanhoyer',
    'http://www.linkedin.com/in/maycheung',
    'http://www.linkedin.com/in/adelinetai',
    'http://www.linkedin.com/in/nathanmehl'
]
