redfin_people = [
    'Mark Carr',
    'Jim Lamb',
    'Krystin Tate',
    'Andy Taylor',
    'Taylor Connolly',
    'Tasha Aquino',
    'Bryan Selner',
    'Kate Ross',
    'Scott Nagel',
    'Michael Young',
    'Jennifer Chao',
    'Eric Hollenbeck',
    'Kristin Thorpe',
    'Glenn Kelman',
    'Llewellyn Botelho',
    'Timothy Ellis',
    'Sonal Basu',
    'Patrick Tsao',
    'Vincent Chang',
    'Mike Brauwerman'
]

redfin_urls = [
    'http://www.linkedin.com/in/markcarr',
    'http://www.linkedin.com/in/jimplamb',
    'http://www.linkedin.com/in/krystin',
    'http://www.linkedin.com/in/andyataylor',
    'http://www.linkedin.com/in/taylorconnolly',
    'http://www.linkedin.com/in/tashaaquino',
    'http://www.linkedin.com/in/bryanselner',
    'http://www.linkedin.com/in/katerossinseattle',
    'http://www.linkedin.com/in/scottnagel1',
    'http://www.linkedin.com/in/youngmichaelw',
    'http://www.linkedin.com/in/jennifersun1',
    'http://www.linkedin.com/in/ejhollenbeck',
    'http://www.linkedin.com/in/kristinthorpe',
    'http://www.linkedin.com/in/glennkelman',
    'http://www.linkedin.com/in/llewellynb',
    'http://www.linkedin.com/in/thetim',
    'http://www.linkedin.com/in/sonalbasu',
    'http://www.linkedin.com/in/pattsao',
    'http://www.linkedin.com/in/vincechang',
    'http://www.linkedin.com/in/mikebrauwerman'
]
